### ISSUE TITLE
Got the following error on db start up.

### ISSUE THREAD

**Issue by sztankatt** [CSTIB-Hotel/OTCAnalyser#34]
I have deleted the previous database, and on start up I get the following error:

     java.sql.SQLException: Unexpected token: SEARCHNAME in statement [CREATE TABLE savedsearches ( id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY searchName]
	     at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
	     at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source)
	     at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source)
	     at      uk.ac.cam.cstibhotel.otcanalyser.database.Database.createSavedSearchTable(Database.java:138)
	at uk.ac.cam.cstibhotel.otcanalyser.database.Database.<init>(Database.java:75)
	at uk.ac.cam.cstibhotel.otcanalyser.database.Database.getDB(Database.java:52)
	at      uk.ac.cam.cstibhotel.otcanalyser.networklayer.InitialUpdateWorker.run(InitialUpdateWorker.java:28)
     There was a fatal database error, class 1
'''

**Comment by waiwaing** [comment]
Please check that you have pulled from the most recent database commit; this should have been fixed earlier.

**Comment by sztankatt** [comment]
Yes, I have the latest version, still getting the error

**Comment by waiwaing** [comment]
In createSavedSearchTable() is there a comma at the end of the second line of the SQL query?

**Comment by sztankatt** [comment]
No... I assume there should be one

**Comment by waiwaing** [comment]
Yes--you haven't pulled from the database branch.

**Comment by sztankatt** [comment]
Yes, Mybad.. I'll merge it into dataanalysis
