### ISSUE TITLE
Casting Integer to String... so that we can parse it into an int?

### ISSUE THREAD

**Issue by waiwaing** [CSTIB-Hotel/OTCAnalyser#37]
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at uk.ac.cam.cstibhotel.otcanalyser.communicationlayer.CommunicationLayer.search(CommunicationLayer.java:56)
	at uk.ac.cam.cstibhotel.otcanalyser.gui.SearchButtonListener.actionPerformed(SearchButtonListener.java:14)

**Comment by seansaville** [comment]
0339b102acdf2c283e30c65057eca6db8c1e501c reverts the change that caused this.
